import { StyleSheet } from 'react-native';
import { Colors, Gaps, Radius } from '../../shared/tokens';

export default StyleSheet.create({
	container: {
		flex: 1,
	},
	emptyContainer: {
		flex: 1,
		paddingHorizontal: Gaps.g24,
		justifyContent: 'center',
		alignItems: 'center',
	},
	emptySendButton: {
		width: '100%',
		height: 44,
		backgroundColor: Colors.orange,
		borderRadius: Radius.medium,
		alignItems: 'center',
		justifyContent: 'center',
		marginTop: Gaps.g8,
	},
	loadingContainer: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
	},
	loadingText: {
		marginTop: Gaps.g16,
		fontSize: 16,
		color: Colors.gray,
	},
	title: {
		fontSize: 24,
		fontWeight: '600',
		color: Colors.black,
		marginBottom: Gaps.g20,
		textAlign: 'center',
	},
	headerContainer: {
		flexDirection: 'row',
		position: 'absolute',
		top: 64,
		left: '50%',
		transform: [{ translateX: '-15%' }],
		right: 0,
	},
	typingContainer: {
		flexDirection: 'row',
		position: 'absolute',
		top: 40,
		left: 20,
	},
	header: {
		fontSize: 18,
		fontWeight: '600',
		color: Colors.black,
		textAlign: 'center',
	},
	subHeader: {
		fontSize: 28,
		fontWeight: '600',
		color: Colors.black,
		textAlign: 'left',
	},
	connectionStatus: {
		marginLeft: Gaps.g8,
		backgroundColor: Colors.gray100,
		paddingHorizontal: Gaps.g8,
		paddingVertical: 4,
		borderRadius: Radius.small,
	},
	connectionStatusText: {
		fontSize: 12,
		color: Colors.gray600,
		minWidth: 62,
	},
	messagesList: {
		flexGrow: 1,
		padding: Gaps.g16,
	},
	messageContainer: {
		marginBottom: Gaps.g16,
		flexDirection: 'column',
		maxWidth: '80%',
	},
	userMessageContainer: {
		alignSelf: 'flex-end',
	},
	aiMessageContainer: {
		alignSelf: 'flex-start',
	},
	messageTextContainer: {
		borderRadius: Radius.medium,
		padding: Gaps.g12,
		marginTop: Gaps.g8,
	},
	messageTextContainerAi: {
		marginTop: 20,
	},
	userMessageText: {
		color: Colors.white,
		backgroundColor: Colors.orange,
		borderRadius: Radius.medium,
		padding: Gaps.g12,
	},
	aiMessageText: {
		color: Colors.black,
		backgroundColor: Colors.gray100,
		borderRadius: Radius.medium,
		padding: Gaps.g12,
	},
	messageText: {
		fontSize: 15,
		lineHeight: 20,
	},
	messageTime: {
		fontSize: 12,
		color: Colors.gray600,
		alignSelf: 'flex-end',
		marginTop: 4,
	},
	inputFooterContainer: {
		flexDirection: 'row',
		paddingVertical: Gaps.g8,
		paddingBottom: Gaps.g2,
		alignItems: 'center',
		backgroundColor: Colors.white,
		width: '100%',
	},
	contentContainer: {
		flex: 1,
		flexDirection: 'column',
		width: '100%',
	},
	content: {
		display: 'flex',
		flexDirection: 'column',
		gap: Gaps.g48,
		alignItems: 'center',
		marginBottom: 60
	},
	card: {
		width: '100%',
		backgroundColor: Colors.white,
		borderRadius: Radius.medium,
		padding: Gaps.g16,
		paddingVertical: 20,
		alignItems: 'flex-start',
		justifyContent: 'center',
		boxShadow: '0px 4px 20px 0px rgba(79, 79, 79, 0.15)',
		display: 'flex',
		flexDirection: 'column',
		gap: Gaps.g12,
	},
	cardTitle: {
		fontSize: 24,
		fontWeight: '600',
		color: Colors.black,
	},
	cardDescription: {
		fontSize: 16,
		color: Colors.gray,
	},
	neuralImg: {
		width: 260,
		height: 260,
	},
	input: {
		borderWidth: 1,
		borderRadius: Radius.medium,
		borderColor: Colors.gray100,
		flex: 1,
		padding: Gaps.g8,
		fontSize: 15,
		minHeight: 40,
	},
	uploadButton: {
		width: 200,
		height: 200,
		borderWidth: 2,
		borderColor: Colors.gray200,
		borderStyle: 'dashed',
		borderRadius: Radius.medium,
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: Gaps.g24,
	},
	uploadButtonText: {
		marginTop: Gaps.g8,
		fontSize: 16,
		color: Colors.gray,
	},
	// photoPreview: {
	// 	flex: 1,
	// 	alignItems: 'center',
	// 	justifyContent: 'center',
	// 	backgroundColor: Colors.white,
	// 	alignSelf: 'stretch'
	// },
	removePhotoButton: {
		position: 'absolute',
		top: 8,
		right: 8,
		backgroundColor: 'rgba(0, 0, 0, 0.5)',
		borderRadius: 20,
		width: 36,
		height: 36,
		justifyContent: 'center',
		alignItems: 'center',
	},
	photoButton: {
		flex: 1,
		height: 44,
		borderRadius: Radius.medium,
		backgroundColor: Colors.gray100,
		justifyContent: 'center',
		alignItems: 'center',
		flexDirection: 'row',
		gap: Gaps.g8,
	},
	photoButtonText: {
		fontSize: 14,
		color: Colors.gray,
	},
	photoButtonSmall: {
		flex: 0.3,
		height: 44,
		borderRadius: Radius.medium,
		backgroundColor: Colors.gray100,
		justifyContent: 'center',
		alignItems: 'center',
	},
	photoPreviewSmall: {
		flex: 0.3,
		height: 44,
		borderRadius: Radius.medium,
		overflow: 'hidden',
		position: 'relative',
	},
	photoPreviewSmallImage: {
		width: '100',
		height: '50',
		marginBottom: Gaps.g8,
	},
	removePhotoSmallButton: {
		position: 'absolute',
		top: 0,
		left: 0,
		backgroundColor: 'rgba(0, 0, 0, 0.5)',
		borderRadius: 8,
		width: 16,
		height: 16,
		justifyContent: 'center',
		alignItems: 'center',
	},
	photoContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: Gaps.g8,
		paddingTop: 0,
		marginTop: 0,
		width: '100%',
	},
	sendButtonContainer: {
		flex: 0.7,
		marginLeft: Gaps.g8,
		height: 44,
		marginBottom: 16,
	},
	sendButton: {
		height: 48,
		paddingHorizontal: Gaps.g16,
		paddingVertical: Gaps.g12,
	},
	sendButtonTextWrapper: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'flex-start',
		justifyContent: 'space-between',
	},
	sendButtonText: {
		textAlign: 'center',
		color: Colors.white,
		fontSize: 16,
		fontWeight: '600',
	},
	messagePhotoContainer: {
		borderRadius: Radius.medium,
		overflow: 'hidden',
	},
	messagePhoto: {
		width: 200,
		height: 150,
		backgroundColor: Colors.gray100,
	},
	messageTimeContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'flex-end',
		marginTop: 4,
		gap: 4
	},

	outOfBalance: {
		header: {
			flexDirection: 'row',
			alignItems: 'center',
			justifyContent: 'flex-start',
			gap: 4,
			marginBottom: Gaps.g24,
		},
		headerTitle: {
			fontSize: 28,
			fontWeight: '600',
			color: Colors.black,
		},
		subtitle: {
			fontSize: 22,
			color: Colors.gray,
			textAlign: 'left',
			fontWeight: '600',
			marginBottom: Gaps.g16,
		},
		description: {
			fontSize: 16,
			color: Colors.gray,
			textAlign: 'left',
			marginBottom: Gaps.g24,
		},

		balanceContainer: {
			flexDirection: 'column',
			alignItems: 'center',
			justifyContent: 'center',
			gap: Gaps.g16,
			backgroundColor: Colors.gray97,
			borderRadius: Radius.medium,
			padding: Gaps.g12,
			paddingTop: Gaps.g24,
		},
		icons: {
			flexDirection: 'row',
			alignItems: 'center',
			justifyContent: 'center',
			gap: 16,
			height: 70,
			width: 200,
		},
		icon1: {
			position: 'absolute',
			top: 0,
			left: 0,
			width: 129,
			height: 129,
		},
		icon2: {
			position: 'absolute',
			top: 0,
			right: 0,
			width: 129,
			height: 129,
		},
		balanceCard: {
			flexDirection: 'column',
			alignItems: 'center',
			justifyContent: 'center',
			gap: Gaps.g12,
			backgroundColor: Colors.white,
			borderRadius: Radius.medium,
			paddingHorizontal: Gaps.g4,
			paddingVertical: Gaps.g24,
			width: '100%',
			opacity: 0.85,
		},
		balanceCardTitle: {
			fontSize: 16,
			color: Colors.black,
			textAlign: 'center',
		},
		balanceCardValue: {
			fontSize: 32,
			color: Colors.black,
			textAlign: 'center',
			fontWeight: '600',
		},
		button: {
			position: 'absolute',
			bottom: Gaps.g24,
			left: 0,
			right: 0,
		},
	},
	inputContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'flex-start',
		backgroundColor: Colors.gray97,
		borderRadius: Radius.medium,
		minHeight: 120,
		padding: Gaps.g12,
		marginBottom: Gaps.g24,
	},
	combinedInput: {
		flex: 1,
		fontSize: 14,
		color: Colors.black,
		paddingTop: 0,
		textAlignVertical: 'top',
	},
	attachButton: {
		width: 20,
		height: 20,
		justifyContent: 'center',
		alignItems: 'center',
		marginRight: Gaps.g8,
	},
}); 